# Generated by Django 5.1.4 on 2025-01-17 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrowing',
        ),
    ]
