# Generated by Django 5.1.4 on 2025-02-05 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
