# Generated by Django 5.1.4 on 2025-02-05 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
