# Generated by Django 5.1.4 on 2025-02-08 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_borrowing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrowing',
        ),
    ]
