# Generated by Django 5.1.4 on 2025-02-07 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_userprofile_stripe_customer_id'),
    ]

    operations = [
    ]
