# Generated by Django 5.1.4 on 2025-02-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_auto_20250207_2050'),
    ]

    operations = [
    ]
