# Generated by Django 5.1.4 on 2025-02-08 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_auto_20250207_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_borrow_per_month',
        ),
    ]
