# Generated by Django 5.1.4 on 2025-02-09 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_remove_subscriptionplan_max_borrow_per_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscription'),
        ),
    ]
