# Generated by Django 5.1.4 on 2025-02-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_alter_borrowing_subscription'),
    ]

    operations = [
    ]
