# Generated by Django 5.1.4 on 2025-02-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_is_read'),
    ]

    operations = [
    ]
