# Generated by Django 5.1.4 on 2025-01-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_product_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_borrowed',
            field=models.BooleanField(default=False),
        ),
    ]
